### ISSUE TITLE
libtask: Make it work correctly with exceptions

### ISSUE THREAD

**Issue by sebastien** [sebastien/k7#1]
For now, when throwing an exception from C/C++ code when libtask is enabled makes k7 core dump

**Comment by gritzko** [comment]
You mean a C++ exception?

**Comment by sebastien** [comment]
No only -- for instance if you compile K7 -DWITH_LIBTASK=1 and that you remove the var print = system.k7.shell.print line from the libtask test, you'll get a coredump. There's probably a way around this, so I've contacted libtask author for more info.

It's a major bug as any runtime error could lead to a segfault.

**Comment by sebastien** [comment]
As of

```
commit 941f79493eb813a86dff3e4126192080ac89a28c
Author: Sebastien Pierre <sebastien@type-z.org>
Date:   Thu Jun 11 12:24:52 2009 -0400
```

There is no segfault, but the exception is not caught either...

**Comment by sebastien** [comment]
Libtask will be incompatible with libevent (and probably with libev as well), so I'll have to remove it (sadly).
