### ISSUE TITLE
modules: enable dyld support and compilation of modules as .so objects

### ISSUE THREAD

**Issue by sebastien** [sebastien/k7#3]
It would help reduce K7 binary size and allow to spread loading time over a larger period

**Comment by gritzko** [comment]
As far as I may see, due to static linking the size of the executable equals the size of v8.
Making small .so files for every module will hardly improve the situation. 
I think, linking to v8 dynamically will improve the situation in many cases.

**Comment by gritzko** [comment]
P.S. But once we''ll have modules for another 10 shared libraries it will make sense to compile modules as .so files. By loading them on demand we avoid those 80% of libraries that are not used by a program. That is years ahead. Currently, compile-time flags work perfectly.

**Comment by sebastien** [comment]
Ooops... I didn't see your second response, we totally agree on that :) dyld support is not top priority but I'd like to get it working just to make sure we won't have to change all modules later to add the infrastructure.

**Comment by gritzko** [comment]
AFAIK, if modules are .so then v8 must be dynamically linked too, as modules also need to link to the library.

**Comment by sebastien** [comment]
I'm not sure, but I don't think so, as the symbols will be available in the program namespace once the code is exectued. However, there is a need to provide a "module registration callback" that grants access to things like the current V8 context and the K7 primitives.

**Comment by sebastien** [comment]
Implemented in 6eb164dc9c01bca25ff96dcd6dd1f79888c6ec05
