### ISSUE TITLE
Argument macros

### ISSUE THREAD

**Issue by gritzko** [sebastien/k7#5]
Old-style parameter macros look ugly when instantiated in big numbers, allow an unnecessary degree of freedom (parameter indexes).

```
#define ARG_obj(v,i)  v8::Local<v8::Object> v=args[i]->ToObject();
```

leads to
    ARG_COUNT(4);
    ARG_utf8(data,0);
    ARG_int(size,1);
    ARG_int(nmemb,2);
    ARG_obj(fileObj,3);

ARGINT-style macros may add too much overhead.

Need a new syntax, e.g.
    FUNCTION(some_function, P_int(a), P_str(b), P_obj(c)) {
        // a will be an int, b will be a str and c will be an obj
    } END
plus pluggable error processing code, e.g.
    #define ARGS_INVALID return JS_undefined;

**Comment by sebastien** [comment]
was imlemented by gritko, merged in b708da07d54443daeba54e04db7eea8880532302
