### ISSUE TITLE
Remove python & scons dependencies from the k7 makefile 

### ISSUE THREAD

**Issue by lpsantil** [sebastien/k7#6]
To me, having python & scons required to build k7 (and v8) is barrier to making k7 more portable.  To remove, python & scons, the following is needed:
- A little bit of OS & CPU (uname) to pick the right platform files for v8
- Some makefile magic to do the libraries-empty.cc => libraries.cc compilation from the v8 JS library files
- js2h python script replaced by a C/C++ file and jsmin.c from http://www.crockford.com/javascript/jsmin.html

I have some notes on this and was working on this in a private tree.

**Comment by lpsantil** [comment]
js2c build process notes:

For every js in src (except d8), do cpp substitution with macros.h (taken from
   macros.py and rewritten in C)

Take output and jsmin

Take output and convert to C char byte array

Take output and cpp substitution into libraries.cc using libraries-empty.cc (taken from js2c.py as embedded template and rewritten as C) with some metainfo about natives :
- source lines arrays named after js files minus .js and -delay.js of the form: static const char name[] = { srcBytes };
- BuiltinCount (number of original js files)
- DelayCount (number of original js files with -delay in name)
- IndexList (basenames minus -delay.js & .js of original js files and index of name)
- ScriptSourceSize (basenames minus -delay.js & .js of original js files and index of name + index + jsmin size)
- ScriptName (basenames + strlen of basenames + index);
- NOTE: Order is important and delays come first (debug, mirror, date, regexp, runtime, v8native, array, string, uri, math, messages, apinatives)

**Comment by sebastien** [comment]
Seems like a lot of work for an unclear benefit, but it might be interesting !

**Comment by lpsantil** [comment]
Part of the reason why I was working on this was that I was developing this code on chroot jailed web host that provides linux, gcc/g++, php, perl, but a really old version of python.  Essentially, to keep developing w/v8, I had to build about 8 different packages to get python and scons working and then install them to a path in my home dir (/home/lpsantil/sw , similar to how fink does apt-get in Mac OSX).  It kind of suck especially when the build process isn't so tricky.

**Comment by sebastien** [comment]
I see, but this seems like a very particular situation -- I agree that the building of K7 should be as simple as possible, but changing the V8 build system seems to me as out of scope from the K7 perspective.

**Comment by lpsantil** [comment]
No problem.  I'll keep working on this in my own time and will share when I get it done.

**Comment by sebastien** [comment]
not really on the plan.
