### ISSUE TITLE
Rewrite macros to be more C/C++ like

### ISSUE THREAD

**Issue by lpsantil** [sebastien/k7#7]
I'd like to be able to write glue code in a manner similar to this.

OBJECT( posix_FILE, 1, FILE\* file )

{

   OBJECT_SCOPE_START();

   OBJECT_INTERNAL_SETUP( 1 );

   INTERNAL( 0, file );

   return( self );

};

FUNCTION( posix_fputs )

{

   SCOPE_START();

   ARG_utf8( str, 0 );

   ARG_obj( fObj, 1 );

   EXTERNAL( FILE*, file, fObj, 0 );

   return( JS_int( fputs( *str, file ) ) );

}

**Comment by gritzko** [comment]
You mean (1) C++ brackets and (2) one macro corresponds to one v8 API call. Right?

**Comment by sebastien** [comment]
K7 modules now use brackets like FUNCTION() { } END to preserve indentation in some editors.

Regarding the macros, if they are just a 1-1 mapping of the V8 API I don't see any necessity for them anymore -- we would just need a V8 cookbook ;)

The spirit of the macros is that they should be as neutral as possible and hide V8 internals to the developer. It makes it easier for contributors as they have less new concepts to learn, and makes it easier to people willing to port K7 modules to other JS implementations.

**Comment by lpsantil** [comment]
I guess I'm just not a fan of having "keyword-ish" macros like END, MODULE, END_MODULE that seem to float around in the code and aren't followed by a parameter list (parens) or a semicolon.  Also, SCOPE_START() clearly lets a developer declare a scope in v8 (which happens in many places in k7.cpp also) but it can be ifdef'd to a blank should k7 ever get ported to another JS engine.

**Comment by gritzko** [comment]
Planning for future porting to some unspecified engine is a dangerous pitfall :)
I'd prefer to have very simple v8-only bindings. Just make it cheap.
"Portability is for people who cannot write new programs."

```
  1 FUNC(posix_fread,ARGINT(size),ARGINT(entries),ARGWRAP(FILE*,file))
  2 {
  3     if (size < 0)
  4         THROW("Exception: invalid bufsize");
  5     char *buf   = malloc(size*entries);
  6     size_t read = fread(buf, size, nmemb, file);
  7     v8::Handle<v8::String> strbuf = JS_str2(buf, read*size);
  8     free(buf)
  9     return SCOPEUP(strbuf);
 10 }
 11 CNUF
 12 FUNC(posix_fopen,ARGSTR(path),ARGSTR(mode))
 13 {
 14     FILE* fd = fopen(*path,*mode);
 15     if (fd == NULL)
 16         return JS_null;
 17     return WRAP(FILE*,fd);
 18 }
 19 CNUF
```

**Comment by sebastien** [comment]
I like this proposal -- I'd prefer to have FUNCTION and END instead of FUNC/CNU, but otherwise I like it. It would be even better to have shorter syntaxes ARGINT could be AINT or PINT P=Parameter, which is different than A=Argument. Parameters are formal placeholders for arguments which are actual values.

**Comment by lpsantil** [comment]
I'd like to see k7 work with SpiderMonkey but that should probably be captured in a different issue.

As for portability, choosing not to design with portability in mind would mean you're choosing not to share the benefits of your work with some people.  And the whole purpose of libraries, SDKs, APIs is to let many benefit from the work of a few.  And for now, there's 1000x more libraries written for SpiderMonkey than for v8.

I agree with sebastien and would only ask that naming be consistent with the other macros like MODULE/END_MODULE, CLASS/END_CLASS.

**Comment by gritzko** [comment]
Here they are, the new shiny macros!
http://github.com/gritzko/k7/blob/73f3d5d6bb30e23af8d13ebc739bc218f0119789/lib/system/event/event.cpp

```
86 FUNCTION(evbuf_read,PWRAP(evbuffer,buf),PINT(file_des),PINT(max_bytes)) {
87     size_t justread = evbuffer_read(buf,file_des,max_bytes);
88     RETURN_INT(justread);
89 } END
```

**Comment by sebastien** [comment]
It looks really good, thanks ! Could you update to the latest K7 version so I can merge everything easily ?

**Comment by gritzko** [comment]
Just merged it on my side.

**Comment by sebastien** [comment]
I've checked it out, it looks really good (except the mix of tabs and spaces in macros.h). I'd do a final review before integrating this (today or tomorrow). Thanks !

**Comment by sebastien** [comment]
Accepted and merged.
