### ISSUE TITLE
libevent: does not work with libevent 1

### ISSUE THREAD

**Issue by sebastien** [sebastien/k7#9]
Libevent 1 is the default on most systems. If libevent 2 is better, then we should ship it with K7 and embed it in the deps so that it gets compiled as a dependency and then statically linked.

I'd personnaly prefer that the event module uses libevent1 by default and then has an option to use libevent2.

**Comment by gritzko** [comment]
On one hand, some systems have ridiculously outdated libevent, so embedding might be wiser. On the other hand, libevent2 has compatibility headers. I'll explore that.

**Comment by sebastien** [comment]
I've added automatic download and compilation of latest libevent in ecdf93469a83fb5da70fdefb34c22853177c0530 -- however, the examples do not work.
